server:
  port: 80


spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#---
#server:
#  port: 8081
#
#spring:
#  profiles: dev
#
#---
#
#server:
#  port:  8080
#spring:
#  profiles: prod
#---
