server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.type: trace
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/jpa?useUnicode=true&autoReconnect=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456